src/webapp/auth.py
# We will place the endpoints here
# This is only used for login, logout, register
from bcrypt import checkpw, gensalt, hashpw
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user

from webapp.progress_handler import add_starting_entry_of

from . import db  # imports from __init__.py
from .models import User

auth = Blueprint("auth", __name__)


# Landing Page
# Access it like this: (url_for('views.landing_page'))
@auth.route("/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("views.landing_page"))

    if request.method == "POST":
        user_name = request.form.get("userName")
        password = request.form.get("password")
        print(user_name, password)

        # Check if the user is in the database
        # user = User.find_user_by_username(user_name, user_manager.load_users_from_file())
        user = User.query.filter_by(
            username=user_name
        ).first()  # visszadja az összes felhasználót akinek az az emailje

        if user:
            # Check if the password matches
            if checkpw(password.encode("utf8"), user.password.encode("utf8")):
                # flash('Sikeres bejelentkezés!', category='succes')
                login_user(
                    user, remember=True
                )  # Megjegyzi a bejelentkezést, addig amíg a szerver újra nem indul
                return redirect(
                    url_for("views.landing_page")
                )  # blueprint.function name
            else:
                flash("Hibás felhasználónév vagy jelszó!", category="error")
        else:
            flash("Hibás felhasználónév vagy jelszó!", category="error")

    return render_template("login.html")


@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("auth.login"))  # blueprint.function name


@auth.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("views.landing_page"))

    if request.method == "POST":
        user_name = request.form.get("userName")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        print(user_name, password1, password2)

        # Check if the user already exists, and other checks
        # user = User.find_user_by_username(user_name, user_manager.load_users_from_file())
        user = User.query.filter_by(
            username=user_name
        ).first()  # returns all the users with the same name

        if user:
            flash("Ez a felhasználónév már használatban van!", category="error")
        # ellenőrzéseket csinálunk
        elif len(user_name) < 4:
            flash(
                "A felhasználónévnek legalább 6 karakter hosszúnak kell lennie.",
                category="error",
            )
        elif password1 != password2:
            flash("A jelszavak nem eggyeznek meg!", category="error")
        elif len(password1) < 7:
            flash(
                "A jelszó legalább 7 karakterből kell, hogy álljon!", category="error"
            )
        else:
            # Register and add to the database
            # new_user = User(9, user_name, hashpw(password1.encode('utf8'), gensalt()).decode())
            new_user = User(
                username=user_name,
                password=hashpw(password1.encode("utf8"), gensalt()).decode(),
            )

            add_starting_entry_of(user_name)

            db.session.add(new_user)
            db.session.commit()
            flash("Sikeres regisztráció!", category="succes")
            # Redirect to home page
            return redirect(url_for("auth.login"))  # blueprint.function name

    return render_template("register.html")

src/webapp/views.py
# We will place the endpoints here
# ex. landing page, dictionary etc...
import random
from sqlite3 import IntegrityError
from flask_login import current_user, login_required
from flask import Blueprint, jsonify, render_template, flash, request

from webapp.progress_handler import calculate_scores, get_grade, update_score_of_user_of_game
from .models import Word, Category
from . import db  # imports from __init__.py
import json
from sqlalchemy import exc, func

views = Blueprint("views", __name__)


# Landing Page
# Access it like this: (url_for('views.landing_page'))
@views.route("/home")
@login_required
def landing_page():
    return render_template("landing_page.html", user=current_user)


@views.route("/progress")
@login_required
def progress():
    scores = calculate_scores(current_user.username)
    # scores = (10, 20, 30, 40, 50)
    (szokirako, szokartyak, egeszitsdki, listening, parositas, sum) = scores
    grade = get_grade(sum)
    return render_template(
        "elorehaladas.html",
        user=current_user,
        szokirako_score=szokirako,
        szokartyak_score=szokartyak,
        egeszitsdki_score=egeszitsdki,
        listening_score=listening,
        parositas_score=parositas,
        sum_score=sum,
        grade_letter=grade,
    )


@views.route("/download-data", methods=["GET"])
@login_required
def download_data():
    scores = calculate_scores(current_user.username)
    (szokirako, szokartyak, egeszitsdki, listening, parositas, sum) = scores
    grade = get_grade(sum)
    data = {
        "Felhasználó": current_user.username,
        "Összesítés": {"Százalék": str(sum) + "%", "Osztályzat": grade},
        "Elért eredmények": {
            "Szókirakó": str(szokirako) + "%",
            "Szókártyák": str(szokartyak) + "%",
            "Egészítsd Ki": str(egeszitsdki) + "%",
            "Listening": str(listening) + "%",
            "Szópárosítás": str(parositas) + "%",
        },
    }
    return jsonify(data)


@views.route("/word_cards")
@login_required
def word_cards():
    translations = {
        "cat": "macska",
        "dog": "kutya",
        "you": "te",
        "did": "csinálta",
        "yes": "igen",
        "never": "soha",
        "far": "messze",
        "apple": "alma"
    }
    new_translations = {
        "mouse": "egér",
        "blue": "kék",
        "picture": "kép",
        "browser": "kereső",
        "question": "kérdés",
        "pen": "toll",
        "purple": "lila",
        "plant": "növény",
    }
    return render_template("szokartya.html", user=current_user, words=translations.keys(), translations=translations, new_words=new_translations.keys(), new_translations=new_translations)

@views.route("/words_pair")
@login_required
def words_pair():
    words_data = Word.query.order_by(func.random()).limit(16)

    pairs = [{'left': word.hungarian_word, 'right': word.english_word} for word in words_data]

    def shuffle_and_extract(pair_list):
        words_left = [pair['left'] for pair in pair_list]
        words_right = [pair['right'] for pair in pair_list]
        random.shuffle(words_left)
        random.shuffle(words_right)
        return words_left, words_right, pair_list

    main_leftWords, main_rightWords, main_correctPairs = shuffle_and_extract(pairs[:8])
    new_leftWords, new_rightWords, new_correctPairs = shuffle_and_extract(pairs[-8:])

    print(pairs)

    return render_template('szoparosit.html', user=current_user, leftWords=main_leftWords, rightWords=main_rightWords,
                           correctPairs=main_correctPairs, new_leftWords=new_leftWords, new_rightWords=new_rightWords,
                           new_correctPairs=new_correctPairs)

@views.route("/pop_up/<string:text>/<string:game>/<string:wonpoints>/<string:tries>")
@login_required
def popup(text, game, wonpoints, tries):
    print("args ==================", text, game, wonpoints, tries)
    flash(text, 'succes')
    update_score_of_user_of_game(username=current_user.username, game=game, wonpoints=int(wonpoints), tries=int(tries))
    return render_template('popup_window.html', user=current_user)
    
    
@views.route("/complete_it")
@login_required
def complete_it():
    return render_template('complete_it.html', user=current_user)

@views.route("/Listening")
@login_required
def Listening():
    return render_template('Listening.html', user=current_user)


@views.route("/dropWordTable")
def dropT():
    Word.__table__.drop(db.engine)
    return "ok"


@views.route("/add_word/<eng>/<hun>")
def add_word(eng, hun):
    newWord = Word(
        english_word=eng,
        hungarian_word=hun
    )

    try:
        db.session.add(newWord)
        db.session.commit()
        return jsonify(str("Word has been added to the DB: " + eng + " " + hun))
    except exc.IntegrityError:
        return jsonify("Unique constraint failed!")
    except:
        return jsonify("There was an error.")


@views.route("/getWords")
@login_required
def getWords():
    words = Word.query.all()

    return jsonify([word.serialize() for word in words])


@views.route("/getWords/<filterBy>")
@login_required
def getWordsByFilter(filterBy):
    filterBy = filterBy.lower()
    words = Word.query.join(Category).filter(
        (Word.english_word.ilike(f"%{filterBy}%")) |
        (Word.hungarian_word.ilike(f"%{filterBy}%")) |
        (Category.english_name == filterBy) |
        (Category.hungarian_name == filterBy)
    ).all()

    return jsonify([word.serialize(filterBy) for word in words])


@views.route("/dictionary")
@login_required
def dictionary():
    words = Word.query.all()
    for word in words:
        print(word.english_word + " " + word.hungarian_word)

    return render_template('dictionary.html', user=current_user)

src/webapp/templates/Listening.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VerbVenture</title>
    <link rel="stylesheet" type="text/css" href="../static/styles/Listening.css">
    {% include 'embeddables/_dynamic_background.html' %}

</head>

<script>
    var correctAnswer = "cat";
    var jovalasz=false;
    let wonpointscounter = 0;
    let triescounter = 0;
    

    document.addEventListener('DOMContentLoaded', function () {
        var area = document.getElementById("writeing");
    
    
    
    const keszButton = document.querySelector('.kesz');
    

    keszButton.addEventListener("click",function(){
        const userAnswer = document.getElementById("writeing").value;
        console.log(userAnswer)
        if (correctAnswer == userAnswer.trim()) {
            area.style.transition = 'background-color 1s ease';
            area.style.backgroundColor = '#00FF00';
            jovalasz=true;
            triescounter++;
            wonpointscounter++;
        } else {
            area.style.transition = 'background-color 1s ease';
            area.style.backgroundColor = '#FF0000';
            jovalasz=false;
            triescounter++;
            setTimeout(function () {
                area.style.backgroundColor = '';
            }, 1500);
        }
    });
    
    const elorehaladasElem = document.querySelector('.elorehaladas');
    const nextButton = document.querySelector('.next');
    let progress = 0;
    let isFirstClick = 0;

    nextButton.addEventListener('click', function() {
        
        if(jovalasz==true){
        isFirstClick += 1;
        progress += 100;
        }
        // Korlátozzuk a progress-bar szélességét, hogy ne menjen ki a div-ből
        if (progress > 100) {
            progress = 100;
        }

        elorehaladasElem.querySelector('.progress-bar').style.width = `${progress}%`;

        console.log(triescounter)
        console.log(wonpointscounter)
    if (isFirstClick == 1) {
        console.log(triescounter)
        console.log(wonpointscounter)
        /*document.getElementById("writeing").value="";
        jovalasz="false";
        document.getElementById("writeing").style.backgroundColor="";
        */
        let url = "{{ url_for('views.popup', text='Visszatérés a főoldalra...', game='Listening', wonpoints='__won__', tries='__tries__') }}";
        url = url.replace('__won__', wonpointscounter).replace('__tries__', triescounter);
        window.location.href = url;
    } if (isFirstClick == 2) {
        console.log(triescounter)
        console.log(wonpointscounter)
        let url = "{{ url_for('views.popup', text='Visszatérés a főoldalra...', game='Listening', wonpoints='__won__', tries='__tries__') }}";
        url = url.replace('__won__', wonpointscounter).replace('__tries__', triescounter);
        window.location.href = url;


}
/*if(isFirstClick==1){
        correctAnswer = "dog";
    }
*/

});
    });
function playAudio() {
    var audio = document.getElementById("hang");
    audio.play();
}
</script>

<body>

    <div class="header">
        <div class="user">
            <p>felhasználó neve</p>
        </div>
        <div class="title"><h1>Listening</h1></div>
        <div class="elorehaladas">
            <div class="progress-bar"></div>
            <p>előrehaladás</p>
        </div>
        </div>

        <main>
            <div class="kozep">
                <button class="listening" onclick="playAudio()"><audio id="hang" src="{{ url_for('static', filename='voices/hangfelolvas/hang1.mp3') }}"></audio><div id="image"><img src="../static/images/speaker.png" alt="felolvasás" title="felolvas"></div></button>
                <div id="textAreas">
                    <textarea id="writeing" name="writeing"  rows="100%" cols="100%">
                     
                    </textarea>
                    
                </div>
                <button class="kesz"><p>Ellenörzés</p></button>
            </div>
            <div class="footer">

                <button class="exit" id="backbutton" class="clickable" onclick="location.href='{{ url_for( 'views.landing_page') }}'"><img src="{{ url_for('static',filename='img/svg-path.svg') }} "></button>
                <button class="next"><p>Tovább</p></button>
            </div>
        </main>
</body>
</html>

src/webapp/templates/_embedded_background_selector.html
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles/background_selector.css') }}">

<div class="bgSelectorModal modal fade" id="backgroundModal" tabindex="-1" aria-labelledby="backgroundModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="backgroundModalLabel">Válassz egy háttérképet!</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{{ url_for('settings.set_background') }}">

                    <div class="row row-cols-1 row-cols-md-3 g-4" id="backgroundImagesFill">

                    </div>
                    <div class="modal-footer justify-content-center">
                        <button type="submit" class="btn btn-primary" name="preferred_background" value="{{ image }}">Mentés</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>


<script>
    document.getElementById('backgroundModal').addEventListener('shown.bs.modal', function () {
        console.log("Background selector window opened");
        $.ajax({
            type: 'GET',
            url: '/get_background_images',
            success: function(data) {
                $('#backgroundImagesFill').html(data);
            }
        });
    })
</script>

src/webapp/templates/complete_it.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VerbVenture</title>
    <link rel="stylesheet" type="text/css" href="../static/styles/complete_it.css">
    {% include 'embeddables/_dynamic_background.html' %}
    


<script>

    var joValasz = false;
    function valasz(element){
        console.log("clicked");
        if(element.classList.contains("jo")){
            console.log("clicked jo");
            element.style.transition = 'background-color 1s ease';
            element.style.color = '#00FF00';
            joValasz = true;
        }
        if(element.classList.contains("rossz")){
            console.log("clicked rossz");
            element.style.transition = 'background-color 1s ease';
            element.style.color = '#FF0000';
            joValasz = false;
        }

        setTimeout(function () {
                        element.style.color = '';
                        },1500);
    }
</script>


<script>
    let wonpointscounter = 0;
    let triescounter = 0;

    document.addEventListener('DOMContentLoaded', function() {
    const elorehaladasElem = document.querySelector('.elorehaladas');
    const nextButton = document.querySelector('.next');
    let progress = 0;
    let isFirstClick = 0;

    nextButton.addEventListener('click', function() {
        console.log(joValasz)
        console.log(isFirstClick)
        if(joValasz==true){
        isFirstClick += 1;
        progress += 50;
        wonpointscounter++;
        triescounter++;
        } else {
            triescounter++;
        }
        // Korlátozzuk a progress-bar szélességét, hogy ne menjen ki a div-ből
        if (progress > 100) {
            progress = 100;
        }

        elorehaladasElem.querySelector('.progress-bar').style.width = `${progress}%`;

        if (isFirstClick === 0) {
            var word = document.querySelector('.szoveg');
            word.style.display = 'flex';
            var answer = document.querySelector('.answers');
            answer.style.display = 'flex';
        
            var word = document.querySelector('.new_szoveg');
            word.style.display = 'none';
            var answer = document.querySelector('.new_answers');
            answer.style.display = 'none';
            
        
    } if (isFirstClick == 1) {
            var word = document.querySelector('.szoveg');
            word.style.display = 'none';
            var answer = document.querySelector('.answers');
            answer.style.display = 'none';
        
            var word = document.querySelector('.new_szoveg');
            word.style.display = 'flex';
            var answer = document.querySelector('.new_answers');
            answer.style.display = 'flex';
            joValasz=false
    } if (isFirstClick == 2) {
    let url = "{{ url_for('views.popup', text='Visszatérés a főoldalra...', game='EgeszitsdKi', wonpoints='__won__', tries='__tries__') }}";
    url = url.replace('__won__', wonpointscounter).replace('__tries__', triescounter);
    
    window.location.href = url;
}

});
    });
</script>
</head>

<body>

    <div class="header">
        <div class="user">
            <p>{{ user.username }}</p>
        </div>
        <div class="title"><h1>Egészítsd ki</h1></div>
        <div class="elorehaladas">
            <div class="progress-bar"></div>
            <p>előrehaladás</p>
        </div>
        
    </div>

        <main>
            <div class="szoveg">
                <p>We have a very __________ day</p>
            </div>
            <div class="answers">
                <button class="clickable jo answer" onclick="valasz(this)"><p>bad</p></button>
                <button class="clickable rossz answer" onclick="valasz(this)"><p>lake</p></button>
                <button class="clickable rossz answer" onclick="valasz(this)"><p>word</p></button>
                <button class="clickable rossz answer" onclick="valasz(this)"><p>cat</p></button>
            </div>
            
            <div class="szoveg new_szoveg">
                <p>This is a sentence, but there is one _______ missing.</p>
            </div>
            <div class="answers new_answers">
                <button class="clickable rossz answer" onclick="valasz(this)"><p>ocean</p></button>
                <button class="clickable rossz answer" onclick="valasz(this)"><p>dog</p></button>
                <button class="clickable jo answer" onclick="valasz(this)"><p>word</p></button>
                <button class="clickable rossz answer" onclick="valasz(this)"><p>baby</p></button>
            </div>

            <div class="footer">
                <button class="exit" id="backbutton" class="clickable" title="kilépés" onclick="location.href='{{ url_for( 'views.landing_page') }}'"><img src="{{ url_for('static',filename='img/svg-path.svg') }} "></button>
                <button class="next">Tovább</button>
            </div>
        </main>
</body>
</html>

src/webapp/templates/dictionary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VerbVenture</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/dictionary.css') }}">
    {% include 'embeddables/_dynamic_background.html' %}
</head>
<body>
    <main>
        <header>
            <div id="userinfo">id: <span id="username">{{ current_user.username }}</span></div>
            <h1>Szótár</h1>
            <div></div>
        </header>

        <div class="content">
            <input type="text" id="searchInput" placeholder="Keresés...">
            <div class="word-list" id="wordList">
            </div>
        </div>

        <button id="backbutton" class="clickable" onclick="location.href='{{ url_for( 'views.landing_page') }}'">
            <img src="{{ url_for('static',filename='img/svg-path.svg') }} ">
        </button>
    </main>
    <script src = "{{ url_for('static',filename='js/timer.js') }}"></script>
    <script src="{{ url_for('static', filename='js/dictionary.js') }}"></script>

</body>
</html>

src/webapp/templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VerbVenture</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/css/landing_page.css') }}">
	{% include 'embeddables/_dynamic_background.html' %}
</head>
<body onLoad="startTime()">
    <main>
        <header>
            <div id="userinfo">id: <span id="username">{{ current_user.username }}</span></div>
            <h1>VerbVenture</h1>
            <div id="control_buttons">
                <button id="logout" class="clickable" onclick="location.href='{{ url_for( 'auth.logout') }}'">Kijelentkezés</button>
                <button id="backgroundChange" onclick="location.href='{{ url_for( 'settings.background_selector') }}'" class="clickable">Háttérkép változtatás</button>
                <button id="time">00:00</button>
            </div>
        </header>
        <div id="nav_buttons">
            <button id="szokartyak" onclick="location.href='{{ url_for( 'views.word_cards') }}'" class="clickable">Szókártyák</button>
            <button id="szoparositas" onclick="location.href='{{ url_for( 'views.words_pair') }}'" class="clickable">Szópárosítás</button>
            <button id="egeszitsd_ki" onclick="location.href='{{ url_for( 'views.complete_it') }}';" class="clickable">Egészítsd ki</button>
            <button id="szotar" onclick="location.href='{{ url_for( 'views.dictionary') }}';" class="clickable">Szótár</button>
            <button id="listening" onclick="location.href='{{ url_for( 'views.Listening') }}';" class="clickable">Listening</button>
            <button id="szokirako" onclick="location.href='szokirako.html';" class="disabled" disabled>Szókirakó</button>
            <button id="elorehaladas" onclick="location.href='{{ url_for( 'views.progress') }}'" class="clickable">Előrehaladás</button>
        </div>
    </main>
    <script src = "{{ url_for('static',filename='js/timer.js') }}"></script>
</body>
</html>

src/webapp/templates/login.html
{% extends "base_template.html" %}
{% block title %}Login{% endblock %}
{% block content %}

    <div class="vh-100 d-flex justify-content-center align-items-center">

        <div class="card h-75 w-50 customCard ">
            <div class="card-body">

                <h1 class="text-center mb-5 mt-3">VerbVenture</h1>

                <form method="POST" class="mb-3 mt-md-4">
                    <div class="mb-3">&nbsp;</div>

                    <div class="form-floating mb-4">
                        <input type="text" class="form-control" id="userName" name="userName" placeholder="John Doe">
                        <label for="floatingInput">Felhasználónév</label>
                    </div>

                    <div class="form-floating mb-4">
                        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                        <label for="floatingPassword">Jelszó</label>
                    </div>

                    <div class="d-grid">
                        <button id="loginButton" class="btn btn-dark" type="submit">Bejelentkezés</button>
                    </div>

                </form>

                <div class="d-grid">
                    <a id="registerButton" class="btn btn-dark" href="{{url_for('auth.register')}}" role="button">Regisztráció</a>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

src/webapp/templates/szokartya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VerbVenture</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/css/szokartya.css') }}">
    {% include 'embeddables/_dynamic_background.html' %}
    <script>
     var translations = JSON.parse('{{ translations | tojson | safe }}');
    console.log(translations)
    
    let wonpointscounter = 0;
    let triescounter = 0;

    function changeWord(element, event) {
        console.log(event.target)

        if (event.target.classList.contains("speak")) {
            return;
        }


    

        console.log("clicked");

        var pElement = element.querySelector('p');
        var currentText = pElement.textContent.trim(); // trim to remove leading/trailing whitespaces

        console.log("Current text:", currentText);

        // Check if the original text is in the translations
        // Toggle between the original and translated words
        if (translations.hasOwnProperty(currentText)) {
            pElement.textContent = translations[currentText];
        } else {
            // Handle the case when the current text is a translated word
            for (var key in translations) {
                if (translations.hasOwnProperty(key) && translations[key] === currentText) {
                    pElement.textContent = key;
                    break;
                }
            }
        }
    }
    document.addEventListener('DOMContentLoaded', function() {
    const elorehaladasElem = document.querySelector('.elorehaladas');
    const nextButton = document.querySelector('.next');
    const backButton = document.querySelector('.back');
    let progress = 0;
    let isFirstClick = 0;
 
    backButton.addEventListener('click', function () {
        isFirstClick = 0; // Mindig az első lépést kezelje, ha a .back elemre kattintanak
        progress = 0;

        translations = JSON.parse('{{ translations | tojson | safe }}');

        document.querySelectorAll('.words').forEach(function (word) {
            word.style.display = 'flex';
        });

        document.querySelectorAll('.new_words').forEach(function (newWord) {
            newWord.style.display = 'none';
        });
    });
    nextButton.addEventListener('click', function() {







        isFirstClick += 1;
        progress += 50;

        // Korlátozzuk a progress-bar szélességét, hogy ne menjen ki a div-ből
        if (progress > 100) {
            progress = 100;
        }

        elorehaladasElem.querySelector('.progress-bar').style.width = `${progress}%`;

        translations = JSON.parse('{{ new_translations | tojson | safe }}');
        if (isFirstClick == 0){
            // Az első kattintásra az összes '.words' elem kiválasztása és a stílusok alkalmazása
            document.querySelectorAll('.words').forEach(function(word) {
                word.style.display = 'flex';
            });

            // Az első kattintásra az összes '.new_words' elem kiválasztása és a stílusok alkalmazása
            document.querySelectorAll('.new_words').forEach(function(newWord) {
                newWord.style.display = 'none';
            });
        } if (isFirstClick == 1) {
            // Az első kattintásra az összes '.words' elem kiválasztása és a stílusok alkalmazása
            document.querySelectorAll('.words').forEach(function(word) {
                word.style.display = 'none';
            });

            // Az első kattintásra az összes '.new_words' elem kiválasztása és a stílusok alkalmazása
            document.querySelectorAll('.new_words').forEach(function(newWord) {
                newWord.style.display = 'flex';
            });
            wonpointscounter += 8;
            triescounter += 8;
        } if (isFirstClick == 2) {
            wonpointscounter += 8;
            triescounter += 8;
            let url = "{{ url_for('views.popup', text='Visszatérés a főoldalra...', game='Szokartyak', wonpoints='__won__', tries='__tries__') }}";
            url = url.replace('__won__', wonpointscounter).replace('__tries__', triescounter);

            
            window.location.href = url;
        }

    });
});
    
    //  HANGÉRT FELELŐS RÉSZ:
function playAudio(index, isNew) {
    var audioIdPrefix = isNew ? 'new_audio' : 'audio';
    var audio = document.getElementById(audioIdPrefix + index);
    audio.play();
}

    </script>

</head>
<body>
    <div class="header">
    <div class="user">
        <p>{{ user.username }}</p>
    </div>
    <div class="title"><h1>Szókártyák</h1></div>
    <div class="elorehaladas">
        <div class="progress-bar"></div>
        <p>előrehaladás</p>
    </div>
    </div>
    <main>
        <div class="backtop"><button class="back" title="vissza az előző szókártyákhoz">Vissza</button></div>
        {% for word in words %}
        <div class="words givesscore" onclick="changeWord(this, event)" data-hang="hang{{ loop.index }}.mp3">
            <p> {{word}} </p>
            <img src="{{ url_for('static', filename='img/speaker.png') }}" alt="felolvasás" title="felolvas" onclick="playAudio({{ loop.index }}, false)" class="speak">
            <audio id="audio{{ loop.index | string }}" src="{{ url_for('static', filename='voices/hang/hang' + loop.index | string + '.mp3') }}"></audio>
        </div>
        {% endfor %}
        {% for word in new_words %}
        <div class="words new_words givesscore" onclick="changeWord(this, event)" data-hang="new_hang{{ loop.index }}.mp3">
            <p> {{word}} </p>
            <img src="{{ url_for('static', filename='img/speaker.png') }}" alt="felolvasás" title="felolvas" onclick="playAudio({{ loop.index }}, true)" class="speak">
            <audio id="new_audio{{ loop.index | string  }}" src="{{ url_for('static', filename='voices/new_hang/hang' + loop.index | string + '.mp3') }}"></audio>
        </div>
        {% endfor %}
        <div class="footer">
            <button class="exit" id="backbutton" title="kilépés" class="clickable" onclick="location.href='{{ url_for( 'views.landing_page') }}'"><img src="{{ url_for('static',filename='img/svg-path.svg') }} "></button>
            <button class="next">Tovább</button>
        </div>
    </main>




</body>
</html>